#!/usr/bin/env python3
"""Render results/*.json into results/REPORT.md (one row per test, newest run first)."""

import json
from pathlib import Path

RESULTS = Path(__file__).resolve().parent.parent / "results"


def fmt(v, spec):
    return format(v, spec) if isinstance(v, (int, float)) else "–"


def main():
    runs = sorted(RESULTS.glob("*_llama_*.json"), reverse=True)
    membw = sorted(RESULTS.glob("*_membw.json"), reverse=True)

    lines = ["# Benchmark report", "", "Generated by `tools/report.py` from `results/*.json`.", ""]
    if membw:
        m = json.loads(membw[0].read_text())
        lines += ["## Achievable memory bandwidth (latest `membw`)", "",
                  "| read | write | copy | cudaMemcpy D2D | theoretical |", "|---:|---:|---:|---:|---:|",
                  f"| {m['read_gbs']:.1f} GB/s | {m['write_gbs']:.1f} GB/s | {m['copy_gbs']:.1f} GB/s "
                  f"| {m['memcpy_d2d_gbs']:.1f} GB/s | 102.4 GB/s |", ""]

    lines += ["## LLM inference", "",
              "| run | model | label | power mode | test | t/s | ± | avg W | J/token | mem BW GB/s "
              "| % theor. | % achiev. | GPU % | GPU MHz | RAM peak MB | GPU max °C |",
              "|---|---|---|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|"]
    for path in runs:
        r = json.loads(path.read_text())
        run = path.name.split("_")[0]
        for t in r["tests"]:
            tel, d = t["telemetry"], t["derived"]
            lines.append(
                f"| {run} | {r['model_file']} | {r['label'] or '–'} | {r['system']['power_mode']} | {t['test']} "
                f"| {t['tokens_per_s']:.1f} | {t['tokens_per_s_stddev']:.1f} "
                f"| {fmt(tel.get('power_vdd_in_w_avg'), '.1f')} | {fmt(d.get('j_per_token'), '.3f')} "
                f"| {fmt(tel.get('mem_bw_gbs_avg'), '.1f')} | {fmt(d.get('mem_bw_pct_theoretical'), '.0f')} "
                f"| {fmt(d.get('mem_bw_pct_achievable_read'), '.0f')} | {fmt(tel.get('gpu_util_pct_avg'), '.0f')} "
                f"| {fmt(tel.get('gpu_mhz_avg'), '.0f')} | {fmt(tel.get('ram_used_mb_max'), '.0f')} "
                f"| {fmt(tel.get('temp_gpu_c_max'), '.1f')} |")
    (RESULTS / "REPORT.md").write_text("\n".join(lines) + "\n")
    print(f"wrote {(RESULTS / 'REPORT.md').name} ({len(runs)} runs)")


if __name__ == "__main__":
    main()
